api:
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /opt/traefik_v2/config.yml

certificatesResolvers:
  http:
    acme:
      email: {{ cloudflare.email }}
      storage: /opt/traefik_v2/acme.json
      httpChallenge:
        entryPoint: http