#########################################################################
# Title:         Pre-Tasks: Clean Paths Task                            #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Clean Paths | Remove trailing slash from new downloads paths
  set_fact:
    downloads:
      nzbs: "{{ (downloads.nzbs | default('',true)) | regex_replace('\\/$', '') }}"
      torrents: "{{ downloads.torrents | regex_replace('\\/$', '') }}"
  when: (downloads is defined) and (downloads.nzbs is defined) and (downloads.torrents is defined)
