#########################################################################
# Title:         Hetzner: Reload GRUB Handler                           #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# https://github.com/debops/ansible-grub
- name: Reload GRUB
  command: grub-mkconfig -o /boot/grub/grub.cfg
  register: grub_register_update
  failed_when: ('error' in grub_register_update.stderr)
