##########################################################################
# Title:         Cloudbox: Plex | Forced Automatic Quality Settings      #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
#   Based on the work by Michael Zemsky (https://github.com/zmike808)    #
##########################################################################
---
- name: Settings | Forced Quality | Install lxml pip module
  pip: "name=lxml state=present"

- name: Settings | Forced Quality | Wait for 'Preferences.xml' to be created by Plex
  wait_for:
    path: "/opt/plex/Library/Application Support/Plex Media Server/Preferences.xml"
    state: present

# 'forceAutoAdjustQuality' in Preferences.xml
# Forces clients to use automatic quality for media unless the quality is set higher than the quality of the video.

- name: "Settings | Forced Quality | Set 'forceAutoAdjustQuality' in 'Preferences.xml' to
    '{{ (plex.force_auto_adjust_quality|default(false,true)) | ternary('Enabled','Disabled') }}'."
  xml:
    path: "/opt/plex/Library/Application Support/Plex Media Server/Preferences.xml"
    xpath: /Preferences
    attribute: forceAutoAdjustQuality
    value: "{{ (plex.force_auto_adjust_quality|default(false,true)) | ternary('1','0') }}"
    state: present
  register: x
  ignore_errors: yes

# 'AllowHighOutputBitrates' in Preferences.xml
# Forces transcode quality to upscale. But can cause high bandwidth usage for clients.

- name: "Settings | Forced Quality | Set 'AllowHighOutputBitrates' in 'Preferences.xml' to
    '{{ (plex.force_high_output_bitrates|default(false,true)) | ternary('Enabled','Disabled') }}'."
  xml:
    path: "/opt/plex/Library/Application Support/Plex Media Server/Preferences.xml"
    xpath: /Preferences
    attribute: AllowHighOutputBitrates
    value: "{{ (plex.force_high_output_bitrates|default(false,true)) | ternary('1','0') }}"
    state: present
  register: y
  ignore_errors: yes

- name: Settings | Forced Quality | Restart plex container
  docker_container:
    name: plex
    state: started
    restart: yes
  when: ('plex_forced_quality' in ansible_run_tags) and (x.changed or y.changed)
