#########################################################################
# Title:         Cloudbox: Rclone - Preinstall Tasks                    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Preinstall | Display message when kernel has been updated"
  debug:
    msg: "Kernel was updated."
  when: (preinstall_kernel_restart is defined) and (preinstall_kernel_restart)

- name: "Preinstall | Display message when cloudbox folder location has been migrated"
  debug:
    msg:
      - "Cloudbox folder was migrated to a new home location."
      - "Re-login with the '{{ user.name }}' account and run the Cloudbox installer from the '{{ new_home_path }}/cloudbox/' path."
  when: (preinstall_user_relogin is defined) and (preinstall_user_relogin)

- name: "Preinstall | Cloudbox pre-install has completed!"
  debug:
    msg: "Cloudbox pre-install has completed!"

- name: Preinstall | Tasks for kernel restart
  block:

  - name: "Preinstall | Display message when restarting server"
    debug:
      msg: "Restarting the server to apply changes..."

  - name: "Preinstall | Reboot"
    shell: reboot

  - name: "Preinstall | Reboot Manually"
    debug:
      msg:
        - "Failed to reboot automatically."
        - "You will need to restart the server yourself for changes to take effect."

  when: (preinstall_kernel_restart is defined) and (preinstall_kernel_restart)
