#########################################################################
# Title:         Cloudbox: Rclone - Uninstall Legacy Rclone Tasks       #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
# Uninstalls Rclone install from /opt/rclone/ from early Cloudbox days.
---
- name: Uninstall Legacy Rclone | Delete '/usr/sbin/rclone' if it exists
  file:
    path: "/usr/sbin/rclone"
    state: absent

- name: Uninstall Legacy Rclone | Check if '/opt/rclone/rclone.conf' exists
  stat:
    path: "/opt/rclone/rclone.conf"
  register: opt_rclone_conf

- name: Uninstall Legacy Rclone | Import 'rclone.conf' to proper place.
  block:

  - name: Uninstall Legacy Rclone | Check if '/home/{{ user.name }}/.config/rclone/rclone.conf' exists
    stat:
      path: "/home/{{ user.name }}/.config/rclone/rclone.conf"
    register: home_rclone_conf

  - name: Uninstall Legacy Rclone | Delete '/home/{{ user.name }}/.config/rclone/rclone.conf' if it is symlinked
    file:
      path: "/home/{{ user.name }}/.config/rclone/rclone.conf"
      state: absent
    when: (home_rclone_conf.stat.islnk is defined) and (home_rclone_conf.stat.islnk)

  - name: Uninstall Legacy Rclone | Copy '/opt/rclone/rclone.conf' to '/home/{{ user.name }}/.config/rclone/rclone.conf'
    copy:
      src: "/opt/rclone/rclone.conf"
      dest: "/home/{{ user.name }}/.config/rclone/rclone.conf"
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
      mode: 0775
      force: no
    when: (not home_rclone_conf.stat.exists) or ((home_rclone_conf.stat.islnk is defined) and (home_rclone_conf.stat.islnk))

  when: (opt_rclone_conf.stat.exists)

- name: Uninstall Legacy Rclone | Delete '/opt/rclone' if it exists
  shell: rm -rf /opt/rclone
  args:
    warn: no
