#########################################################################
# Title:         Cloudbox: Kernel Role                                  #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Set default 'reboot_is_necessary' variable
  set_fact:
    reboot_is_necessary: false

- name: Preinstall task
  include_tasks: "subtasks/preinstall.yml"
  when: ('preinstall' in ansible_run_tags)

- name: "Hetzner Tasks"
  import_tasks: "subtasks/hetzner.yml"
  tags: kernel-hetzner

- name: "Cron Tasks"
  include_tasks: "subtasks/cron.yml"

- name: "Mainline Kernel Script Tasks"
  include_tasks: "subtasks/script.yml"

- name: "Update Tasks"
  include_tasks: "subtasks/update.yml"

- name: "Header Tasks"
  include_tasks: "subtasks/headers.yml"

- name: "Restart Tasks"
  include_tasks: "subtasks/restart.yml"
  when: (reboot_is_necessary) and
    (not continuous_integration)

- name: "Checks Tasks"
  include_tasks: "subtasks/checks.yml"
