#########################################################################
# Title:         Cloudbox: Plex Auth Token Role                         #
# Author(s):     EnorMOZ, Desimaniac                                    #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Get X-Plex-Token"
  uri:
    url: https://plex.tv/users/sign_in.json
    method: POST
    headers:
      X-Plex-Version: "1.0.0"
      X-Plex-Product: "cloudbox"
      X-Plex-Client-Identifier: "XXXX"
      Content-Type: "application/x-www-form-urlencoded; charset=utf-8"
    user: '{{ plex.user }}'
    password: '{{ plex.pass }}'
    status_code: 201
  register: plex_token_raw

- name: Display 'Plex Pass' status
  debug:
    msg: "Plex Pass is {{ ('plexpass' in plex_token_raw.json.user.roles.roles) | ternary('enabled','disabled') }}."

- name: Set plex_auth_token variable
  set_fact:
    plex_auth_token: "{{ plex_token_raw.json.user.authToken | regex_replace('\n', '') }}"

- name: Display Plex Auth Token
  debug:
    msg: "Plex Auth Token: {{ plex_auth_token }}"
