#########################################################################
# Title:         Cloudbox: Qbittorrent Role                             #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  binhex/arch-qbittorrentvpn:latest                      #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: qbittorrent
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: qbittorrent
    state: absent

- name: Create qbittorrent directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }} recurse=yes"
  with_items:
    - /opt/qbittorrent
    - /opt/qbittorrent/openvpn
    - /opt/scripts/qbittorrent

- name: Create new downloads directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }} recurse=yes"
  with_items:
    - "{{ downloads.torrents }}/qbittorrent"
    - "{{ downloads.torrents }}/qbittorrent/complete"
    - "{{ downloads.torrents }}/qbittorrent/incomplete"
    - "{{ downloads.torrents }}/qbittorrent/watched"
  when: (torrents_downloads_path is defined)|default(false)

- name: Openvpn configuration
  block:

  - name: Check if opvn config file exists
    stat:
      path: "/opt/qbittorrent/openvpn/config.ovpn"
    register: config_ovpn

  - name: Import 'openvpn config'
    shell: "curl -Lo /opt/qbittorrent/openvpn/config.ovpn '{{ vpn.config }}'"
    become: yes
    become_user: "{{ user.name }}"
    when: not config_ovpn.stat.exists

  when: (vpn.enable|default(false,true))

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/qbittorrent:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"

- name: Create and start container
  docker_container:
    name: qbittorrent
    image: binhex/arch-qbittorrentvpn:latest
    pull: yes
    capabilities:
      - NET_ADMIN
    network_mode: "container:{{ vpn_host }}"
#    published_ports:
#      - "127.0.0.1:8090:8090"
      #- "{{ vpn.port }}:{{ vpn.port }}"
      # jackett port
#      - "127.0.0.1:9117:9117"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: "000"
      VPN_ENABLED: "no"
      VPN_PROV: "airvpn"
      ENABLE_PRIVOXY: "no"
      LAN_NETWORK: "172.18.0.0/16"
      NAME_SERVERS: "209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1"
      ADDITIONAL_PORTS: #"{{ vpn.port }}:{{ vpn.port }}"
      WEBUI_PORT: 8090
      DEBUG: "false"
    volumes: "{{ default_volumes + torrents_downloads_path|default([]) }}"
    labels:
      traefik.enable: "true"
      traefik.backend: "qbittorrent"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:qbittorrent.{{ user.domain }}"
      traefik.port: "8090"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
#    networks:
#      - name: cloudbox
#        aliases:
#          - qbittorrent
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
