#########################################################################
# Title:         Cloudbox: Prowlarr Role                                 #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/prowlarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: prowlarr
  when: cloudflare_enabled

- name: Slurp hashed htpasswd
  slurp:
    src: "/opt/traefik/.htpasswd"
  register: hashed

- name: Set hashed password
  set_fact:
    htpasswd: "{{ hashed['content'] | b64decode }}"

- name: Stop and remove any existing container
  docker_container:
    name: prowlarr
    state: absent

- name: Set vpn host container
  block:

  - name: Check if qbittorrent is using vpn
    stat:
      path: "/opt/qbittorrent/openvpn/config.ovpn"
    register: qbittorrent_vpn

  - name: Set qbittorrent as the vpn host container
    set_fact:
      vpn_host: qbittorrent
    when: qbittorrent_vpn.stat.exists

  - name: Check if sabnzbd is using vpn
    block:

    - name: Check if sabnzbd is using vpn
      stat:
        path: "/opt/sabnzbd/openvpn/config.ovpn"
      register: sabnzbd_vpn

    - name: Set sabnzbd as the vpn host container
      set_fact:
        vpn_host: sabnzbd
      when: sabnzbd_vpn.stat.exists

    when: not qbittorrent_vpn.stat.exists      

  when: (vpn.enable|default(false,true))

- name: Create prowlarr directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/prowlarr

- name: Create and start container
  docker_container:
    name: prowlarr
    image: hotio/prowlarr
    pull: yes
    network_mode: "container:{{ vpn_host }}"
#    published_ports:
#      - "127.0.0.1:9696:9696"
    env:
      BACKUP: "no"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: 002
      TZ: "{{ tz }}"
    volumes:
      - "/opt/prowlarr:/config"
    labels:
      traefik.enable: "true"
      traefik.backend: "prowlarr"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:prowlarr.{{ user.domain }}"
      traefik.port: "9696"
      traefik.frontend.auth.basic: "{{ htpasswd }}"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
#    networks:
#      - name: cloudbox
#        aliases:
#          - prowlarr
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
