########################################################################################
# Title:         Cloudbox: Settings | Migrator | All | Migration 02                    #
# Author(s):     desimaniac                                                            #
# URL:           https://github.com/cloudbox/cloudbox                                  #
# --                                                                                   #
#                 Part of the Cloudbox project: https://cloudbox.works                 #
########################################################################################
#                            GNU General Public License v3.0                           #
########################################################################################
---
- name: Migrator | All | '{{ file }}' | Migration 02 | Add single space after colon (if needed)
  replace:
    path: "{{ playbook_dir }}/{{ file }}"
    regexp: '(:)[ \t]*(.*)'
    replace: '\1 \2'
    owner: "{{ cloudbox_yml.stat.uid }}"
    group: "{{ cloudbox_yml.stat.gid }}"
    mode: 0664

- name: Migrator | All | '{{ file }}' | Migration 02 | Re-import Variables
  include_vars: "{{ playbook_dir }}/{{ file }}"
