#########################################################################
# Title:         Cloudbox: Remote | Sanity Check Tasks                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Sanity Checks | Fail when both plexdrive and mergerfs are enabled."
  fail:
    msg: "Running Plexdrive with MergerFS is not allowed."
  when: (mounts.unionfs | lower == 'mergerfs') and ('plexdrive' in mounts.remote | lower)
