#########################################################################
# Title:         Kernel: Update Task                                    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Update | Update the linux kernel when required
  block:

  - name: Update | Update kernel
    apt:
      name: linux-generic-hwe-16.04
      update_cache: yes
      state: latest
    register: r

  - name: Update | Fix apt
    shell: apt-get --fix-broken --yes install
    when: (r.changed)

  - name: Update | Set 'reboot_is_necessary' variable
    set_fact:
      reboot_is_necessary: true
    when: (r.changed)

  - name: Update | Kernel was updated
    debug:
      msg: "Kernel was updated."
    when: (r.changed)

  - name: Update | Kernel was not updated
    debug:
      msg: "Kernel was not updated."
    when: (not r.changed)

  when: (ansible_distribution == 'Ubuntu') and (ansible_distribution_version is version('16.04', '==')) and (ansible_kernel is version('4.10', '<'))
