#########################################################################
# Title:         Cloudbox: Ombi                                         #
# Author(s):     RXWatcher1, l3uddz, desimaniac                         #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/ombi                                             #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: "{{ ombi.subdomain|default('ombi',true) }}"
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: ombi
    state: absent

- name: Create ombi directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/ombi

- name: Create and start container
  docker_container:
    name: ombi
    image: "hotio/ombi"
    pull: yes
    published_ports:
      - "127.0.0.1:3579:5000"
    env:
      BACKUP: "no"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: 002
      LC_ALL: "en_US.UTF-8"
      TZ: "{{ tz }}"
    volumes:
      - "/opt/ombi:/config"
    labels:
      traefik.enable: "true"
      traefik.backend: "ombi"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:ombi.{{ user.domain }}"
      traefik.port: "5000"
      traefik.frontend.auth.basic: "{{ htpasswd }}"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
#    labels:
#      traefik.enable: "true"
#      traefik.http.routers.ombi.entrypoints: "http"
#      traefik.http.routers.ombi.rule: "Host(`{{ ombi.subdomain|default('ombi',true) }}.{{ user.domain }}`)"
#      traefik.http.middlewares.ombi-https-redirect.redirectscheme.scheme: "https"
#      traefik.http.routers.ombi.middlewares: "ombi-https-redirect"
#      traefik.http.routers.ombi-secure.entrypoints: "https"
#      traefik.http.routers.ombi-secure.rule: "Host(`{{ ombi.subdomain|default('ombi',true) }}.{{ user.domain }}`)"
#      traefik.http.routers.ombi-secure.tls: "true"
#      traefik.http.routers.ombi-secure.tls.certresolver: "cloudflare"
#      traefik.http.routers.ombi-secure.middlewares: "secured@file"
#      traefik.http.routers.ombi-secure.service: "ombi"
#      traefik.http.services.ombi.loadbalancer.server.port: "5000"
#      traefik.docker.network: "cloudbox"
#      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - ombi
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
