#########################################################################
# Title:         Cloudbox: Remote | Plexdrive 4 Tasks                   #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/Cloudbox/Cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Plexdrive 4 | Install mongodb
  apt:
    name: mongodb
    state: present

- name: Plexdrive 4 | Create directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }} recurse=yes"
  with_items:
    - /opt/plexdrive4

- name: Plexdrive 4 | Install plexdrive
  get_url:
    url:  https://github.com/dweidenfeld/plexdrive/releases/download/4.1.0-beta-1498656614/plexdrive-linux-amd64
    dest: /opt/plexdrive4/plexdrive
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Plexdrive 4 | Import 'plexdrive4.service'
  template:
    src: plexdrive4.service.j2
    dest: /etc/systemd/system/plexdrive4.service
    force: "{{ 'yes' if ('mounts_override' in ansible_run_tags) else 'no' }}"

- name: Plexdrive 4 | Systemd daemon-reload 'plexdrive4.service'
  systemd: name=plexdrive4 state=stopped enabled=no daemon_reload=yes

- name: Plexdrive 4 | Check if config exists
  stat:
    path: "/opt/plexdrive4/config.json"
  register: plexdrive4_config

- name: Plexdrive 4 | Start 'plexdrive4.service' if config exists
  systemd: name=plexdrive4 state=started enabled=yes
  when: (plexdrive4_config.stat.exists)
