#########################################################################
# Title:         Cloudbox: ZNC Role                                     #
# Author(s):     l3uddz, horjulf                                        #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  horjulf/docker-znc                                     #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: znc
  when: cloudflare_enabled

- name: Slurp hashed htpasswd
  slurp:
    src: "/opt/traefik_v1/.htpasswd"
  register: hashed

- name: Set hashed password
  set_fact:
    htpasswd: "{{ hashed['content'] | b64decode }}"

- name: Stop and remove any existing container
  docker_container:
    name: znc
    state: absent

- name: Create znc directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/znc

- name: Create and start container
  docker_container:
    name: znc
    image: horjulf/docker-znc
    pull: yes
    published_ports:
      - "127.0.0.1:6501:6501"
      - "6502:6502"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/znc:/config"
    labels:
      traefik.enable: "true"
      traefik.backend: "znc"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:znc.{{ user.domain }}"
      traefik.port: "6501"
      traefik.frontend.auth.basic: "{{ htpasswd }}"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
#    labels:
#      traefik.enable: "true"
#      traefik.http.routers.znc.entrypoints: "http"
#      traefik.http.routers.znc.rule: "Host(`znc.{{ user.domain }}`)"
#      traefik.http.middlewares.znc-https-redirect.redirectscheme.scheme: "https"
#      traefik.http.routers.znc.middlewares: "znc-https-redirect"
#      traefik.http.routers.znc-secure.entrypoints: "https"
#      traefik.http.routers.znc-secure.rule: "Host(`znc.{{ user.domain }}`)"
#      traefik.http.routers.znc-secure.tls: "true"
#      traefik.http.routers.znc-secure.tls.certresolver: "letsEncrypt"
#      traefik.http.routers.znc-secure.middlewares: "secured@file"
#      traefik.http.routers.znc-secure.service: "znc"
#      traefik.http.services.znc.loadbalancer.server.port: "6501"
#      traefik.docker.network: "cloudbox"
#      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - znc
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
