#########################################################################
# Title:         qBittorrent - Settings Task                            #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Stop Container
- name: Wait for qBittorrent.conf to be created
  wait_for:
    path: "/opt/qbittorrent/qBittorrent/config/qBittorrent.conf"
    state: present

- name: "Wait for 10 seconds before stopping qBittorrent container"
  wait_for:
    timeout: 10

- name: Stop container to customize qBittorrent.conf
  docker_container:
    name: qbittorrent
    state: stopped

- name: Import qBittorrent settings
  copy:
    src: "qBittorrent.conf"
    dest: "/opt/qbittorrent/qBittorrent/config/qBittorrent.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: yes

- name: Start container to apply changes
  docker_container:
    name: qbittorrent
    state: started